name: deployment_workflow

on:
  push:
    branches: [main]

jobs:
  deplou:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: testing deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /Users/maxmyers/cmsc389T-fall22/Projects/P5/CMSC389T-Web-Template/CMSC389T-Web-Template
            git pull
